dataset_name: msd_bound
image_path: /PATH_TO_NORMALIZED_IMAGES/imagesTr_normalized
label_path: /PATH_TO_LABELS/labelsTr
edge_path: /PATH_TO_EDGE_LABELS/brats_edges
edge_label: False
image_file_format: npz
label_file_format: nii.gz
train_list_path: ./brats_split_list/train_list_cv0.txt
ignore_path: ./brats_split_list/train_list_cv0_3samples1.txt
validation_list_path: ./brats_split_list/validation_list_cv0.txt
test_list_path: ./brats_split_list/test_list_cv0.txt
crop_size: (144,144,128)
random_flip: True
in_channels: 4
nb_labels: 4
print_each_dc: True
val_batchsize: 1
structseg_nb_copies: 1
shift_intensity: 0.1
segmentor_name: cpcseg
vaeseg_norm: 'GroupNormalization'
seg_lossfun: dice_loss_plus_cross_entropy
cpc_vaeseg_cpc_loss_weight: 0.001 # 0.0005
init_lr: 0.0001
epoch: 300
cpc_pattern: 'updown'
snapshot_interval: 100
random_scale: True
eval_interval: 2
is_brats: True
report_interval: 10
vae_idle_weight: 1
nested_label: True
